
version: "3.5"
services:
  mongodb:
    restart: always
    image: mongo
    container_name: atri_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=atri
    networks:
      atri-net:
        ipv4_address: 192.168.15.2
    volumes:
      - ./resolv.conf:/etc/resolv.conf
      - ./mongo_data:/data/db
    ports:
      - 27017:27017

  atri-api:
    build: ./atri_api
    restart: always
    container_name: atri_api
    ports:
      - 8016:8016
    networks:
      atri-net:
        ipv4_address: 192.168.15.3
    volumes:
      - ./resolv.conf:/etc/resolv.conf
      - ./atri_api/.env:/app/.env:ro
    depends_on: 
      - mongodb
      - redis

  atri-bot:
    restart: always
    build: ./atri_bot
    container_name: atri_bot
    networks:
      atri-net:
        ipv4_address: 192.168.15.4
    volumes:
      - ./resolv.conf:/etc/resolv.conf
      - ./atri_bot/.env:/app/atri_bot/.env
      - ./atri_bot/arof/:/app/atri_bot/utils/arof/
      - ./atri_bot/imsakiyah/:/app/atri_bot/utils/imsakiyah/
    depends_on: 
      - mongodb

  atri-admin:
    restart: always
    build: ./atri_admin
    container_name: atri_admin
    networks:
      atri-net:
        ipv4_address: 192.168.15.5
    volumes:
      - ./resolv.conf:/etc/resolv.conf
      - ./atri_admin/.env:/app/atri_admin/.env
    depends_on: 
      - atri-api

  vndb-scraper:
    restart: always
    build: ./vndb_scraper
    container_name: atri_scraper
    networks:
      atri-net:
        ipv4_address: 192.168.15.6
    volumes:
      - ./resolv.conf:/etc/resolv.conf
      - ./vndb_scraper/.env:/app/vndb_scraper/.env
    depends_on:
      - mongodb
  redis:
    image: 'redis:alpine'
    container_name: atri_redis
    ports:
      - '6379:6379'
    networks:
      atri-net:
        ipv4_address: 192.168.15.7
    volumes:
      - ./redis_data:/data

networks:
  atri-net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.15.0/28
        gateway: 192.168.15.1
    driver_opts:
      com.docker.network.bridge.name: atri-net

secrets:
  mongodb_uri: 
    external: true
